version: '2'
services:
    gayasms-app:
        image: gayasms
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gayasms-mysql:3306/gayasms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://gayasms-elasticsearch:9200
        ports:
            - 8080:8080
    gayasms-mysql:
        extends:
            file: mysql.yml
            service: gayasms-mysql
    gayasms-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gayasms-elasticsearch
